parameters:
    redcode.transaction.manager.flows: []

services:
    redcode.transaction.manager:
        class: RedCode\Transaction\Manager
        arguments: [@doctrine.orm.entity_manager, @event_dispatcher, @logger, @redcode.transaction.flow.manager]

    redcode.transaction.flow.manager:
        class: RedCode\Transaction\Flow\FlowManager
        arguments: [@doctrine, %redcode.transaction.manager.flows%]
